# coding:UTF-8

DEFAULT_LABEL_SIZE = 9
DEFAULT_ENTRY_SIZE = DEFAULT_LABEL_SIZE
DEFAULT_FONT_NAME = "Helvetica"

LABEL_BOLD = (DEFAULT_FONT_NAME, DEFAULT_LABEL_SIZE, 'bold')
ENTRY_DEFAULT = (DEFAULT_FONT_NAME, DEFAULT_ENTRY_SIZE)

MOYEN_DE_PAYEMENT = ['Cash', 'Carte', 'BVR']

labels_text = {
    # Données concernant la fiche du patient
    'id': "ID patient",
    'sexe': "Sexe",
    'therapeute': "Therapeute",
    'nom': "Nom",
    'prenom': "Prenom",
    'naissance_le': "Naissance le (AAAA-MM-JJ)",
    'naissance': "Naissance",
    'date_ouverture': "Date d'ouverture",
    'tel_fix': "Téléphone fixe",
    'medecin': "Médecin traitant",
    'portable': "Portable",
    'tel_prof': "Téléphone professionnel",
    'mail': "Courriel",
    'adr_priv': "Adresse privée",
    'medecinS': "Autres médecins",
    'ass_comp': "Assurance complémentaire",
    'profes': "Profession",
    'etat': "Etat civil",
    'envoye': "Envoyé par",
    'remarques': "Remarques",
    # Données concernant les consultations
    'mc': "Motif(s) de consultation",
    'eg': "Etat general",
    'expc': "Examens paracliniques",
    'atcdp': "Antecedents personnels",
    'atcdf': "Antecedents familiaux",
    'thorax': "Thorax",
    'abdomen': "Abdomen",
    'tete': "Tete et cou",
    'ms': "Membres superieurs",
    'mi': "Membres inferieurs",
    'gen': "Neuro, vascul, dermato, endocrino, lymph",
    'a_osteo': "Anamnese osteopathique",
    'exph': "Examen physique",
    'ttt': "Traitement",
    'important': "Important",
    'paye': "Paye ?",
    'ttes_cons': "Toutes les consultations du patient",
    'seance': "Durée / Prix",
    'paye_par': "Moyen de payement",
    'paye_le': "Payement reçu le",
}
labels_font = {
    'id': LABEL_BOLD,
    'sexe': LABEL_BOLD,
    'therapeute': LABEL_BOLD,
    'nom': LABEL_BOLD,
    'prenom': LABEL_BOLD,
    'naissance_le': LABEL_BOLD,
    'naissance': LABEL_BOLD,
    'date_ouverture': LABEL_BOLD,
    'tel_fix': LABEL_BOLD,
    'medecin': LABEL_BOLD,
    'portable': LABEL_BOLD,
    'tel_prof': LABEL_BOLD,
    'mail': LABEL_BOLD,
    'adr_priv': LABEL_BOLD,
    'medecinS': LABEL_BOLD,
    'ass_comp': LABEL_BOLD,
    'profes': LABEL_BOLD,
    'etat': LABEL_BOLD,
    'envoye': LABEL_BOLD,
    'remarques': LABEL_BOLD,
    'mc': LABEL_BOLD,
    'eg': LABEL_BOLD,
    'expc': LABEL_BOLD,
    'atcdp': LABEL_BOLD,
    'atcdf': LABEL_BOLD,
    'thorax': LABEL_BOLD,
    'abdomen': LABEL_BOLD,
    'tete': LABEL_BOLD,
    'ms': LABEL_BOLD,
    'mi': LABEL_BOLD,
    'gen': LABEL_BOLD,
    'a_osteo': LABEL_BOLD,
    'exph': LABEL_BOLD,
    'ttt': LABEL_BOLD,
    'important': LABEL_BOLD,
    'paye': LABEL_BOLD,
    'ttes_cons': LABEL_BOLD,
    'seance': LABEL_BOLD,
    'paye_par': LABEL_BOLD,
    'paye_le': LABEL_BOLD,
}
fields_font = {
    'id': ENTRY_DEFAULT,
    'sexe': ENTRY_DEFAULT,
    'therapeute': ENTRY_DEFAULT,
    'nom': ENTRY_DEFAULT,
    'prenom': ENTRY_DEFAULT,
    'naissance_le': ENTRY_DEFAULT,
    'naissance': ENTRY_DEFAULT,
    'date_ouverture': ENTRY_DEFAULT,
    'tel_fix': ENTRY_DEFAULT,
    'medecin': ENTRY_DEFAULT,
    'portable': ENTRY_DEFAULT,
    'tel_prof': ENTRY_DEFAULT,
    'mail': ENTRY_DEFAULT,
    'adr_priv': ENTRY_DEFAULT,
    'medecinS': ENTRY_DEFAULT,
    'ass_comp': ENTRY_DEFAULT,
    'profes': ENTRY_DEFAULT,
    'etat': ENTRY_DEFAULT,
    'envoye': ENTRY_DEFAULT,
    'remarques': ENTRY_DEFAULT,
    'mc': ENTRY_DEFAULT,
    'eg': ENTRY_DEFAULT,
    'expc': ENTRY_DEFAULT,
    'atcdp': ENTRY_DEFAULT,
    'atcdf': ENTRY_DEFAULT,
    'thorax': ENTRY_DEFAULT,
    'abdomen': ENTRY_DEFAULT,
    'tete': ENTRY_DEFAULT,
    'ms': ENTRY_DEFAULT,
    'mi': ENTRY_DEFAULT,
    'gen': ENTRY_DEFAULT,
    'a_osteo': ENTRY_DEFAULT,
    'exph': ENTRY_DEFAULT,
    'ttt': ENTRY_DEFAULT,
    'important': ENTRY_DEFAULT,
    'paye': ENTRY_DEFAULT,
    'ttes_cons': ENTRY_DEFAULT,
    'seance': ENTRY_DEFAULT,
    'paye_par': ENTRY_DEFAULT,
    'paye_le': ENTRY_DEFAULT,
}
fields_height = {
    'medecin': 5,
    'adr_priv': 5,
    'medecinS': 8,
    'remarques': 5,
    'mc': 5,
    'eg': 7,
    'expc': 12,
    'atcdp': 5,
    'atcdf': 5,
    'thorax': 5,
    'abdomen': 5,
    'tete': 5,
    'ms': 5,
    'mi': 5,
    'gen': 5,
    'a_osteo': 5,
    'exph': 18,
    'ttt': 8,
    'important': 7,
    'paye': 7,
    'rp': 20,
    'rc': 20,
    'ttes_cons': 40,
}
fields_width = {
    'rp': 75,
    'rc': 75,
}
